# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-09 17:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30, verbose_name='坑主公司')),
                ('desc', models.TextField(verbose_name='坑主描述')),
                ('prov', models.CharField(max_length=20, verbose_name='省份')),
                ('disc', models.CharField(max_length=20, verbose_name='区/乡镇')),
                ('concrate_address', models.TextField(verbose_name='详细地址')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '坑',
                'verbose_name_plural': '坑',
            },
        ),
        migrations.CreateModel(
            name='Hole_people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='坑主名称')),
                ('work_year', models.IntegerField(default=0, verbose_name='工作年龄')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=6, verbose_name='性别')),
                ('occupation', models.CharField(max_length=30, verbose_name='职位')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hole.Hole', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '坑',
                'verbose_name_plural': '坑',
            },
        ),
    ]
