# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-09 17:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radish_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=6, verbose_name='性别')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('work_age', models.IntegerField(default=10, verbose_name='工作年限')),
                ('education_background', models.CharField(choices=[('chuzhong', '初中'), ('zhongji', '中技'), ('gaozhong', '高中'), ('zhongzhuan', '中专'), ('dazhuan', '大专'), ('benke', '本科'), ('shuoshi', '硕士'), ('mba', 'MBA'), ('boshi', '博士'), ('emba', 'EMBA'), ('qita', '其他')], max_length=20, verbose_name='学历')),
                ('address_now', models.CharField(max_length=20, verbose_name='现居住地')),
                ('company_now', models.CharField(max_length=30, verbose_name='当前公司')),
                ('occupation_now', models.CharField(max_length=30, verbose_name='当前职位')),
                ('filename', models.CharField(max_length=20, verbose_name='简历名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='上传时间')),
                ('contact', models.IntegerField(default=12, verbose_name='联系方式')),
                ('image', models.ImageField(upload_to='radish/%Y/m', verbose_name='头像')),
            ],
            options={
                'verbose_name': '萝卜信息',
                'verbose_name_plural': '萝卜信息',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='简历名称')),
                ('file', models.FileField(upload_to='radish/%Y/%m', verbose_name='资源查看或者下载')),
                ('Radish_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radish.Radish_info', verbose_name='萝卜')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
            },
        ),
    ]
