# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-13 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radish_info',
            name='name',
            field=models.CharField(default='NULL', max_length=5, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='resume',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='上传时间'),
        ),
    ]
