# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-13 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180712_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailvertifyrecord',
            name='sendTime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间'),
        ),
    ]
